### ISSUE TITLE
File download doesn't work

### ISSUE THREAD

**Issue by tizot** [TomAugspurger/effective-pandas#9]
When executing the cell with file download from the Transtats website, we do not download a zip file but an HTML page containing:
```<html>
<head>
	<script type="text/javascript" src="js/dot_ostr_analytics.js"></script>
</head>
<body>

start time ==> 5:59:28 PM<br>complete time==> 5:59:28 PM

</body></html>
```

Can you precise which table we should download from the government website?

**Comment by TomAugspurger** [comment]
Thanks. The page is here https://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=236&DB_Short_Name=On-Time

Can you give 2779436a9f33c2c985910226fdf5e8812dd760e8 a shot (just `git pull` on master) That hopefully fixed it for the first one. I'll try to get to the rest sometime, but it will be a bit.

**Comment by tizot** [comment]
OK, it seems to work.
Thank you for this repository! :)
